# Generated by Django 4.2.16 on 2024-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("confirmed", "Confirmed")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
