# Generated by Django 4.2.16 on 2024-12-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_time",
            field=models.TimeField(default="09:00:00"),
        ),
        migrations.AlterField(
            model_name="appointment", name="appointment_date", field=models.DateField(),
        ),
    ]
