# Generated by Django 4.2.16 on 2024-12-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_appointment_appointment_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.CharField(max_length=20),
        ),
    ]
